## configure exporter here
mysql:
  host: "mysql.database-monitoring.svc.cluster.local"
  user: "mysqluser"
  port: 3306
  existingPasswordSecret:
    name: "mysql-secret"
    key: "MYSQL_PASSWORD"

serviceMonitor:
  enabled: true
  additionalLables:
    release: prometheus
